### ISSUE TITLE
Allow switching between blacklist and whitelist for commands

### ISSUE THREAD

**Issue by lerndmina** [WiIIiam278/HuskSync#139]
It'd be nice if for the config `synchronization.blacklisted_commands_while_locked` we could switch between a blacklist and a whitelist, it could look something like this.

```yml
synchronization
  comnmand_blacklist: true
  commands_while_locked: []
```

There's probably a better way to do this in the config.
My main problem is I have a lot of commands that the player shouldn't perform while their data is syncing, especially because I sync location data too.
