### ISSUE TITLE
Max Health not syncing correctly when item attributes are involved

### ISSUE THREAD

**Issue by nicolube** [WiIIiam278/HuskSync#148]
Description:
===
When joining on server maxHealth get reduced to 20 HP (MC default) and player takes max health and health is greather then 20 HP
When HuskSync loads inv, max health gets reset to the amout of hp ur equip gives u, but the heath is not healed.

### Video:
https://youtu.be/XvzdJ4coo98

Exprected:
===
After inv sync, the health is back to the amout it was before server switch.

Our Setup:
===
Vecolity Proxy
 \  Purpur Server cb-1
 \  Purpur Server fw-1
 
 fw-1 / cb-1 have both husksync v2.2.5
 
Tested combinations:
```
max_health: true
health: true
potion_effects: true
```
```
max_health: false
health: true
potion_effects: true
```
```
max_health: false
health: false
potion_effects: true
```
```
max_health: false
health: false
potion_effects: false
```
```
max_health: true
health: false
potion_effects: false
```
```
max_health: true
health: true
potion_effects: false
```
```
max_health: true
health: false
potion_effects: true
```
```
max_health: false
health: true
potion_effects: false
```
```
max_health: true
health: false
potion_effects: true
```

Base Config:
 ```yml
 # ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃        HuskSync Config       ┃
# ┃    Developed by William278   ┃
# ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┣╸ Information: https://william278.net/project/husksync
# ┗╸ Documentation: https://william278.net/docs/husksync
language: de-de
check_for_updates: true
cluster_id: '1'
debug_logging: false
database:
  credentials:
    # Database connection settings
    host: local
    port: 3306
    database: citybuild
    username: citybuild
    password: citybuild
    parameters: ?autoReconnect=true&useSSL=false
  connection_pool:
    # MySQL connection pool properties
    maximum_pool_size: 5
    minimum_idle: 2
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000
  table_names:
    user_data: husksync_user_data
    users: husksync_users
redis:
  credentials:
    # Redis connection settings
    host: local
    port: 6379
    password: ''
  use_ssl: false
synchronization:
  # Synchronization settings
  max_user_data_snapshots: 5
  save_on_world_save: true
  save_on_death: false
  save_empty_drops_on_death: true
  compress_data: true
  notification_display_slot: ACTION_BAR
  synchronise_dead_players_changing_server: true
  network_latency_milliseconds: 500
  features:
    advancements: false
    location: false
    game_mode: true
    potion_effects: true
    locked_maps: true
    inventories: true
    max_health: true
    experience: true
    health: true
    statistics: true
    persistent_data_container: true
    hunger: true
    ender_chests: true
  blacklisted_commands_while_locked: []
  event_priorities:
    quit_listener: LOWEST
    death_listener: NORMAL
    join_listener: LOWEST
```
